"""
3.build_pointcloud.py – Fast TSDF Fusion to Point Cloud
========================================================
Fuses RGB-D frames + pose trajectory into a coloured point cloud (PLY).
Speed-optimised: half-resolution integration, larger voxels, frame
subsampling, and single-pass outlier removal.

Run AFTER  2.pose_tracking.py
Run BEFORE 4.visualize_pointcloud.py
"""

import open3d as o3d
import numpy as np
import cv2
import json
import os
import sys
import time

# ================= Configuration =================
# Point to the dataset folder (same as 1. and 2. – inner folder with rgb/, depth/, calib/)
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.join(SCRIPT_DIR, "dataset")

# Path to the trajectory file generated by 2.pose_tracking.py
TRAJ_FILE = os.path.join(BASE_DIR, "pose_trajectory.txt")
# Output file
OUTPUT_PLY = os.path.join(BASE_DIR, "pointcloud.ply")

# Camera intrinsics (match calib/rgb_intrinsics.json and 2.pose_tracking.py)
WIDTH, HEIGHT = 1280, 720
FX, FY = 613.584, 613.542
CX, CY = 644.171, 355.251

# ---- Speed: integrate at half resolution ----
INT_SCALE = 0.5
INT_W = int(WIDTH * INT_SCALE)   # 640
INT_H = int(HEIGHT * INT_SCALE)  # 360

# Fusion Settings (speed-tuned)
VOXEL_SIZE = 0.008  # 8 mm resolution (was 5 mm – ~4x fewer voxels by volume)
SDF_TRUNC  = 0.032  # 4x voxel size
MAX_DEPTH  = 3.0    # Ignore depth beyond 3 metres
DEPTH_SCALE = 1000.0

# Frame subsampling: minimum seconds between integrated frames
MIN_FRAME_INTERVAL = 0.3   # skip redundant frames (was 0.15)

# Path to RGB intrinsics (has distortion coefs for undistortion)
RGB_INTRINSICS_JSON = os.path.join(BASE_DIR, "calib", "rgb_intrinsics.json")
# =================================================


def load_rgb_intrinsics_and_maps():
    """Load RGB intrinsics and build undistortion maps."""
    path = RGB_INTRINSICS_JSON
    if not os.path.exists(path):
        return None, None
    with open(path, "r") as f:
        calib = json.load(f)
    w, h = int(calib["width"]), int(calib["height"])
    fx, fy = float(calib["fx"]), float(calib["fy"])
    cx, cy = float(calib["cx"]), float(calib["cy"])
    K = np.array([[fx, 0, cx], [0, fy, cy], [0, 0, 1]], dtype=np.float64)
    dist = np.array([
        calib.get("k1", 0), calib.get("k2", 0), calib.get("p1", 0), calib.get("p2", 0),
        calib.get("k3", 0), calib.get("k4", 0), calib.get("k5", 0), calib.get("k6", 0),
    ], dtype=np.float64)
    map1, map2 = cv2.initUndistortRectifyMap(K, dist, None, K, (w, h), cv2.CV_32FC1)
    return (K, (w, h)), (map1, map2)


def load_tum_trajectory(path):
    poses = {}
    if not os.path.exists(path):
        print(f"Error: Trajectory file not found at {path}")
        sys.exit(1)

    with open(path, 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split()
            ts = float(parts[0])
            tx, ty, tz = float(parts[1]), float(parts[2]), float(parts[3])
            qx, qy, qz, qw = float(parts[4]), float(parts[5]), float(parts[6]), float(parts[7])

            R = o3d.geometry.get_rotation_matrix_from_quaternion(np.array([qw, qx, qy, qz]))
            T = np.eye(4)
            T[:3, :3] = R
            T[:3, 3] = [tx, ty, tz]
            poses[ts] = T
    return poses


def read_file_list(filename):
    """Reads rgb.txt or depth.txt.  Converts nanosecond timestamps to seconds."""
    data = {}
    full_path = os.path.join(BASE_DIR, filename)
    if not os.path.exists(full_path):
        return {}
    with open(full_path, 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            parts = line.split()
            t = float(parts[0])
            if t > 1e10:
                t = t / 1e9
            data[t] = parts[1]
    return data


def associate_frames(rgb_list, depth_list, poses, max_diff=0.02):
    """Matches RGB, Depth, and Pose based on timestamps."""
    matches = []
    rgb_ts = sorted(rgb_list.keys())
    depth_ts = sorted(depth_list.keys())
    pose_ts = sorted(poses.keys())

    for t_rgb in rgb_ts:
        t_depth = min(depth_ts, key=lambda t: abs(t - t_rgb))
        if abs(t_depth - t_rgb) > max_diff:
            continue
        t_pose = min(pose_ts, key=lambda t: abs(t - t_rgb))
        if abs(t_pose - t_rgb) > max_diff:
            continue
        matches.append((t_rgb, rgb_list[t_rgb], depth_list[t_depth], poses[t_pose]))
    return matches


def filter_bad_poses(matches, max_translation=3.0, max_jump=0.3):
    """Reject frames whose poses are obviously wrong."""
    filtered = []
    last_good_t = None
    skipped = 0
    for (ts, rgb_file, depth_file, T_wc) in matches:
        t_vec = T_wc[:3, 3]
        if np.linalg.norm(t_vec) > max_translation:
            skipped += 1
            continue
        if last_good_t is not None:
            jump = np.linalg.norm(t_vec - last_good_t)
            if jump > max_jump:
                skipped += 1
                continue
        last_good_t = t_vec.copy()
        filtered.append((ts, rgb_file, depth_file, T_wc))
    if skipped:
        print(f"  Pose filter removed {skipped} frame(s) with suspicious poses.")
    return filtered


def main():
    wall_start = time.time()

    # 1. Camera Intrinsics at integration resolution
    intrinsic = o3d.camera.PinholeCameraIntrinsic(
        INT_W, INT_H,
        FX * INT_SCALE, FY * INT_SCALE,
        CX * INT_SCALE, CY * INT_SCALE)

    calib_info, undistort_maps = load_rgb_intrinsics_and_maps()
    if undistort_maps is None:
        print("Warning: calib/rgb_intrinsics.json not found; skipping undistortion.")
    else:
        print("Loaded RGB intrinsics; will undistort color and depth.")

    # 2. Load Data
    print("Loading file lists...")
    rgb_list = read_file_list("rgb.txt")
    depth_list = read_file_list("depth.txt")
    poses = load_tum_trajectory(TRAJ_FILE)

    matches = associate_frames(rgb_list, depth_list, poses)
    print(f"Found {len(matches)} synchronized frames.")

    matches = filter_bad_poses(matches, max_translation=3.0, max_jump=0.3)
    print(f"After pose sanity filter: {len(matches)} frames kept.")

    # Subsample
    if MIN_FRAME_INTERVAL > 0 and len(matches) > 1:
        subsampled = [matches[0]]
        for m in matches[1:]:
            if m[0] - subsampled[-1][0] >= MIN_FRAME_INTERVAL:
                subsampled.append(m)
        print(f"After subsampling (>= {MIN_FRAME_INTERVAL}s apart): {len(subsampled)} frames.")
        matches = subsampled

    # 3. TSDF Volume
    print(f"Initializing TSDF Volume (voxel {VOXEL_SIZE*1000:.0f} mm, "
          f"integration res {INT_W}x{INT_H})...")
    volume = o3d.pipelines.integration.ScalableTSDFVolume(
        voxel_length=VOXEL_SIZE,
        sdf_trunc=SDF_TRUNC,
        color_type=o3d.pipelines.integration.TSDFVolumeColorType.RGB8
    )

    # 4. Integration Loop
    print("Integrating frames...")
    t_int = time.time()
    for i, (ts, rgb_file, depth_file, T_wc) in enumerate(matches):
        if i % 10 == 0:
            print(f"  frame {i}/{len(matches)}", end='\r')

        color_cv = cv2.imread(os.path.join(BASE_DIR, rgb_file))
        depth_cv = cv2.imread(os.path.join(BASE_DIR, depth_file), cv2.IMREAD_UNCHANGED)
        if color_cv is None or depth_cv is None:
            continue

        # Undistort at full resolution
        if undistort_maps is not None:
            map1, map2 = undistort_maps
            color_cv = cv2.remap(color_cv, map1, map2, cv2.INTER_LINEAR)
            depth_cv = cv2.remap(depth_cv, map1, map2, cv2.INTER_NEAREST)

        # Downscale for speed
        if INT_SCALE != 1.0:
            color_cv = cv2.resize(color_cv, (INT_W, INT_H), interpolation=cv2.INTER_AREA)
            depth_cv = cv2.resize(depth_cv, (INT_W, INT_H), interpolation=cv2.INTER_NEAREST)

        color_raw = o3d.geometry.Image(cv2.cvtColor(color_cv, cv2.COLOR_BGR2RGB))
        depth_raw = o3d.geometry.Image(depth_cv)

        rgbd = o3d.geometry.RGBDImage.create_from_color_and_depth(
            color_raw, depth_raw,
            depth_scale=DEPTH_SCALE,
            depth_trunc=MAX_DEPTH,
            convert_rgb_to_intensity=False
        )

        extrinsic = np.linalg.inv(T_wc)
        volume.integrate(rgbd, intrinsic, extrinsic)

    print(f"\nIntegration done  ({time.time() - t_int:.1f}s). Extracting point cloud...")

    # 5. Extract Point Cloud
    pcd = volume.extract_point_cloud()
    print(f"Raw points: {len(pcd.points)}")

    # 6. Single-pass Statistical Outlier Removal (faster than 2 passes)
    print("Running Statistical Outlier Removal...")
    _, ind = pcd.remove_statistical_outlier(nb_neighbors=25, std_ratio=1.2)
    pcd_clean = pcd.select_by_index(ind)
    print(f"Cleaned points: {len(pcd_clean.points)}")

    # 7. Save
    o3d.io.write_point_cloud(OUTPUT_PLY, pcd_clean)
    elapsed = time.time() - wall_start
    print(f"Saved to {OUTPUT_PLY}")
    print(f"Total wall time: {elapsed:.1f}s")


if __name__ == "__main__":
    main()
